// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtfneqpdflnlrkgwpfpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0Zm5lcXBkZmxubHJrZ3dwZnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODIyNzIsImV4cCI6MjA2Nzk1ODI3Mn0.r53Bcklg3sgLKJWAUNy3q-cbrRlAq8E2ioBckn2U7Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});