// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmcdylnodynsedyyqixi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtY2R5bG5vZHluc2VkeXlxaXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODc1NjksImV4cCI6MjA2Nzk2MzU2OX0.oPf3NTBC8_w70CuyT77_fl31BGhz9McwULLvX2gLdcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});